agregar validaciones en el cd

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -1,11 +1,15 @@
 name: cd
 
 on:
-  release:
-    types: [published]
+  workflow_run:
+    workflows: ["ci"]
+    branches: [main]
+    types:
+    - completed
 
 jobs:
   deploy:
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
     name: Deploy
     runs-on: ubuntu-latest
 
@@ -40,7 +44,7 @@ jobs:
               docker rm test-api
               exit 0
             else
-              echo "⏳ Intento $i: respuesta '$RESPONSE'. Reintentando..."
+              echo "Intento $i: respuesta '$RESPONSE'. Reintentando..."
               sleep 5
             fi
           done
@@ -58,5 +62,17 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/event_hub:latest,${{ secrets.DOCKERHUB_USERNAME }}/event_hub:${{ env.date }}
 
-      - name: Deploy
-        run: curl ${{ secrets.RENDER_HOOK }}
+      - name: Deploy to Render
+        run: |
+          echo "Deployando en Render..."
+          RESPONSE=$(curl --fail --silent --show-error --write-out "%{http_code}" --output /dev/null ${{ secrets.RENDER_HOOK }}) || {
+            echo "❌ Error al hacer deploy. Código HTTP: $RESPONSE"
+            exit 1
+          }
+          if [ "$RESPONSE" -eq 200 ]; then
+            echo "✅ Deploy finalizado exitosamente. Código HTTP: $RESPONSE"
+          else
+            echo "❌ Error inesperado. Código HTTP: $RESPONSE"
+            exit 1
+          }
+
